TiendaDeRopa/urls.py
from django.contrib import admin
from django.urls import path
from Tienda.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('index/', index, name="index"),
    path('about/', about, name="about"),
    path('main/', main, name="main"),
    path('admin-login/', adminLogin, name="admin_login"),
    path('adminhome/', adminHome, name="adminhome"),
    path('admindashboard/', admin_dashboard, name="admindashboard"),
    path('add-category/', add_category, name="add_category"),
    path('view-category/', view_category, name="view_category"),
    path('edit-category/<int:pid>/', edit_category, name="edit_category"),
    path('delete-category/<int:pid>/', delete_category, name="delete_category"),
    path('add-product/', add_product, name='add_product'),
    path('view-product/', view_product, name='view_product'),
    path('edit-product/<int:pid>/', edit_product, name="edit_product"),
    path('delete-product/<int:pid>/', delete_product, name="delete_product"),
    path('registration/', registration, name="registration"),
    path('userlogin/', userlogin, name="userlogin"),
    path('profile/', profile, name="profile"),
    path('logout/', logoutuser, name="logout"),
    path('change-password/', change_password, name="change_password"),
    path('user-product/<int:pid>/', user_product, name="user_product"),
    path('product-detail/<int:pid>/', product_detail, name="product_detail"),
    path('add-to-cart/<int:pid>/', addToCart, name="addToCart"),
    path('cart/', cart, name="cart"),
    path('incredecre/<int:pid>/', incredecre, name="incredecre"),
    path('deletecart/<int:pid>/', deletecart, name="deletecart"),
    path('booking/', booking, name="booking"),
    path('my-order/', myOrder, name="myorder"),
    path('user-order-track/<int:pid>/', user_order_track, name="user_order_track"),
    path('change-order-status/<int:pid>/', change_order_status, name="change_order_status"),
    path('user-feedback/', user_feedback, name="user_feedback"),
    path('manage-feedback/', manage_feedback, name="manage_feedback"),
    path('delete-feedback/<int:pid>/', delete_feedback, name="delete_feedback"),
    path('payment/', payment, name="payment"),
    path('feedback-read/<int:pid>/', read_feedback, name="read_feedback"),
    path('manage-order/', manage_order, name="manage_order"), 
    path('delete-order/<int:pid>/', delete_order, name="delete_order"),
    path('admin-order-track/<int:pid>/', admin_order_track, name="admin_order_track"),
    path('manage-user/', manage_user, name="manage_user"),
    path('delete-user/<int:pid>/', delete_user, name="delete_user"),
    path('admin-change-password/',admin_change_password, name="admin_change_password"),
    path('contact/', contact, name="contact"),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Tienda/models.py
from django.db import models
from django.contrib.auth.models import User

class Carousel(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    image = models.FileField(null=True, blank=True)
    def __str__(self):
        return self.title

class Category(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    image = models.FileField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    price = models.CharField(max_length=100, null=True, blank=True)
    discount = models.CharField(max_length=100, null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
class UserProfile(models.Model):
    user = models.ForeignKey (User, on_delete=models.CASCADE, null=True, blank=True)
    mobile = models.CharField(max_length=100, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    image = models.FileField(null=True, blank=True)
   
    def __str__(self):
        return self.user.username

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    product = models.TextField(default={'objects': []}, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username
    
ORDERSTATUS = (
    (1, "Pendiente"),
    (2, "Despachado"),
    (3, "En camino"),
    (4, "Entregado"),
    (5, "Cancelado"),
    (6, "Devuelto")
)

class Reserva(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    producto = models.TextField(default={'objects': []}, null=True, blank=True)
    total = models.CharField(max_length=100, null=True, blank=True)
    estado = models.IntegerField(choices=ORDERSTATUS, default=1)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.usuario.username

STATUS = ((1, "Leido"), (2, "No leido"))
class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    message = models.TextField(null=True, blank=True)
    status = models.IntegerField(choices=STATUS, default=2)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username
    

Tienda/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from .models import Carousel, Category, Product, User, UserProfile, Cart, Reserva, ORDERSTATUS, Feedback
import json
from django.http import HttpResponse

def home(request):
    return render(request, 'home.html')

def index(request):
    return render(request, 'navegacion.html')

def about(request):
    return render(request, 'acerca_de.html')

def main(request):
    data = Carousel.objects.all()
    dic = {'data': data}
    return render(request, 'index.html', dic)

def adminLogin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None and user.is_staff:
            login(request, user)
            messages.success(request, "Usuario ingresó exitosamente")
            return redirect('admindashboard')
        else:
            messages.error(request, "Credenciales inválidas")
    return render(request, 'admin_login.html')

@staff_member_required
def adminHome(request):
    return render(request, 'admin_inicio.html')

@staff_member_required
def admin_dashboard(request):
    user = UserProfile.objects.filter()
    category = Category.objects.filter()
    product = Product.objects.filter()
    new_order = Reserva.objects.filter(estado=1)  
    dispatch_order = Reserva.objects.filter(estado=2) 
    way_order = Reserva.objects.filter(estado=3) 
    deliver_order = Reserva.objects.filter(estado=4) 
    cancel_order = Reserva.objects.filter(estado=5)
    return_order = Reserva.objects.filter(estado=6) 
    order = Reserva.objects.filter()
    read_feedback = Feedback.objects.filter(status=1)
    unread_feedback = Feedback.objects.filter(status=2)
    return render(request, 'admin_dashboard.html', locals())


@staff_member_required
def add_category(request):
    if request.method == "POST":
        name = request.POST['name']
        Category.objects.create(name=name)
        messages.success(request, "Categoría agregada")
        return redirect('view_category')
    return render(request, 'agregar_categoria.html')

@staff_member_required
def view_category(request):
    category = Category.objects.all()
    return render(request, 'lista_categorias.html', {'category': category})

@staff_member_required
def edit_category(request, pid):
    category = Category.objects.get(id=pid)
    if request.method == "POST":
        name = request.POST['name']
        category.name = name
        category.save()
        messages.success(request, "Categoría actualizada")
        return redirect('view_category')
    return render(request, 'editar_categoria.html', {'category': category})

@staff_member_required
def delete_category(request, pid):
    category = Category.objects.get(id=pid)
    category.delete()
    messages.success(request, "Categoría eliminada")
    return redirect('view_category')

@staff_member_required
def add_product(request):
    category = Category.objects.all()
    if request.method == "POST":
        name = request.POST['name']
        price = request.POST['price']
        cat = request.POST['category']
        discount = request.POST['discount']
        desc = request.POST['desc']
        image = request.FILES['image']
        catobj = Category.objects.get(id=cat)
        Product.objects.create(name=name, price=price, discount=discount, category=catobj, description=desc, image=image)
        messages.success(request, "Producto agregado")
        return redirect('view_product')
    return render(request, 'agregar_producto.html', locals())

@staff_member_required
def view_product(request):
    product = Product.objects.all()
    return render(request, 'lista_productos.html', locals())

@staff_member_required
def edit_product(request, pid):
    product = Product.objects.get(id=pid)
    category = Category.objects.all()
    if request.method == "POST":
        name = request.POST['name']
        price = request.POST['price']
        cat = request.POST['category']
        discount = request.POST['discount']
        desc = request.POST['desc']
        try:
            image = request.FILES['image']
            product.image = image
            product.save()
        except:
            pass
        catobj = Category.objects.get(id=cat)
        Product.objects.filter(id=pid).update(name=name, price=price, discount=discount, category=catobj, description=desc)
        messages.success(request, "Producto actualizado")
        return redirect('view_product')
    return render(request, 'editar_producto.html', locals())

@staff_member_required
def delete_product(request, pid):
    product = Product.objects.get(id=pid)
    product.delete()
    messages.success(request, "Producto eliminado")
    return redirect('view_product')

def registration(request):
    if request.method == "POST":
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        password = request.POST['password']
        address = request.POST['address']
        mobile = request.POST['mobile']
        image = request.FILES['image']
        user = User.objects.create_user(username=email, first_name=fname, last_name=lname, email=email, password=password)
        UserProfile.objects.create(user=user, mobile=mobile, address=address, image=image)
        messages.success(request, "Registro exitoso")
    return render(request, 'registro.html', locals())

def userlogin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            messages.success(request, "Usuario ingresó exitosamente")
            return redirect('home')
        else:
            messages.success(request, "Credenciales inválidas")
    return render(request, 'login.html', locals())

def profile(request):
    data = UserProfile.objects.get(user=request.user)
    if request.method == "POST":
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        address = request.POST['address']
        mobile = request.POST['mobile']
        try:
            image = request.FILES['image']
            data.image = image
            data.save()
        except:
            pass
        user = User.objects.filter(id=request.user.id).update(first_name=fname, last_name=lname)
        UserProfile.objects.filter(id=data.id).update(mobile=mobile, address=address)
        messages.success(request, "Perfil actualizado")
        return redirect('profile')
    return render(request, 'perfil.html', locals())

from django.contrib.auth import authenticate, login, logout

def logoutuser(request):
    logout(request)
    messages.success(request, "Cierre de sesión exitoso")
    return redirect('main')

def change_password(request):
    if request.method == 'POST':
        o = request.POST.get('old')
        n = request.POST.get('new')
        c = request.POST.get('confirm')
        user = authenticate(username=request.user.username, password=o)
        if user:
            if n == c:
                user.set_password(n)
                user.save()
                messages.success(request, "Contraseña cambiada")
                return redirect('main')
            else:
                messages.success(request, "Las contraseñas no coinciden")
                return redirect('change_password')
        else:
            messages.success(request, "Contraseña inválida")
            return redirect('change_password')
    return render(request, 'cambiar_contraseña.html')

def user_product(request,pid):
    if pid == 0:
        product = Product.objects.all()
    else:
        category = Category.objects.get(id=pid)
        product = Product.objects.filter(category=category)
    allcategory = Category.objects.all()
    return render(request, "producto_usuarios.html", locals())

def product_detail(request, pid):
    product = Product.objects.get(id=pid)
    latest_product = Product.objects.filter().exclude(id=pid).order_by('-id')[:10]
    return render(request, "detalles_producto.html", locals())

@login_required(login_url='userlogin')
def addToCart(request, pid):
    myli = {"objects": []}
    try:
        cart = Cart.objects.get(user=request.user)
        myli = json.loads((str(cart.product)).replace("'", '"'))
        try:
            myli['objects'][0][str(pid)] = myli['objects'][0].get(str(pid), 0) + 1
        except:
            myli['objects'].append({str(pid): 1})
        cart.product = myli
        cart.save()
    except Cart.DoesNotExist:
        myli['objects'].append({str(pid): 1})
        cart = Cart.objects.create(user=request.user, product=myli)
    return redirect('cart')
def incredecre(request, pid):
    cart = Cart.objects.get(user=request.user)
    if request.GET.get('action') == "incre":
        myli = json.loads((str(cart.product)).replace("'", '"'))
        myli['objects'][0][str(pid)] = myli['objects'][0].get(str(pid), 0) + 1
    if request.GET.get('action') == "decre":
        myli = json.loads((str(cart.product)).replace("'", '"'))
        if myli['objects'][0][str(pid)] == 1:
            del myli['objects'][0][str(pid)]
        else:
            myli['objects'][0][str(pid)] = myli['objects'][0].get(str(pid), 0) - 1
    cart.product = myli
    cart.save()
    return redirect('cart')

def cart(request):
    try:
        cart = Cart.objects.get(user=request.user)
        product = (cart.product).replace("'", '"')
        myli = json.loads(str(product))
        product = myli['objects'][0]
        empty_cart = len(product) == 0  # Check if cart is empty
    except:

Tienda/templates/acerca_de.html
{% load static %}
<html>
<head>
  <title>Acerca de</title>
  <link rel="stylesheet" href="{% static 'css/about.css' %}"
</head>
<body>
{% include 'navegacion.html' %}
<section class="about-section">
  <div class="container">
    <div class="row">
      <div class="content-column col-lg-6 col-md-12 col-sm-12 order-2">
        <div class="inner-column">
          <div class="sec-title">
            <span class="title">About C.C Clothes</span>
            <h2>We are Creative Tech Enthusiast working since 2015</h2>
          </div>
          <div class="text">I am Your Name works at Your Company Name since last 3 years. We are here to provide
            touch notch solution for your website or web application that helps you to make your website look attractive
            & efficient in handling by creating useful plugins that's you need.
          </div>
          <div class="text">
            We are here to serve you next level tutorial that currently in trend to match you with your expertise. Panjwani
            Tutorials is a learning website. where you can find many good quality content related to web development
            and tutorials about plugins. here we are using html, html5, css, css3, jquery & javascript along with
            inspirational UI design layout by professionals by using Photoshop and adobe allustrator.
          </div>
          <div class="btn-box">
            <a href="{% url 'contact' %}" class="theme-btn btn-style-one">Contact Us</a>
          </div>
        </div>
      </div>
      <!-- Image Column -->
      <div class="image-column col-lg-6 col-md-12 col-sm-12">
        <div class="inner-column wow fadeInLeft">
          <div class="author-desc">
            <h2>Your Name</h2>
            <span>Your Position</span>
          </div>
          <figure class="image-1"><a href="#" class="lightbox-image" data-fancybox="images"><img
                  title="Your Name" src="{% static 'images/about.png' %}" alt=""></a></figure>
        </div>
      </div>

    </div>
    <div class="sec-title">
      <span class="title">Our Future Goal</span>
      <h2>We want to lead in innovation & Technology</h2>
    </div>
    <div class="text">
      We works on UI/UX and functionality as well so that a plugins comes with proper stucture & stunning looks which
      suits to your web app & website.
    </div>
    <div class="text">
      We take a small toolkit here and ride it well so that it is fit for your use. One who performs well and looks even
      better.
    </div>
    <div class="text">
      Here we are trying to give you all kinds of technical content, whether it is related to designing or
      functionality. We are creating content on a lot of languages and will continue to make it free of cost even if you
      use it without any problem. Which is a very important thing.
    </div>
    <div class="text">
      Here you can also share the content you create, if our technical team likes it, then we will also share it on our
      blog.
    </div>
    <div class="text">
      In the end, I would say keep visiting our website and enjoy the quality content.
    </div>
  </div>
</section>
</body>

Tienda/templates/admin_ordenes.html
{% extends 'admin_inicio.html' %}
{% block main %}
{% load custom_tags %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<div class="card shadow">
    <div class="card-body">
        <h5 class="p-2" style="border-bottom: 2px solid orange;">{{order_status}}</h5>
        <div class="container-fluid">
            <table class="table table-bordered table-sm" id="example">
                <thead>
                <tr>
                    <th>No.</th>
                    <th>ID de Orden</th>
                    <th>Nombre</th>
                    <th>Email</th>
                    <th>Estado</th>
                    <th>Acción</th>
                </tr>
                </thead>
                <tbody>
                {% for i in order %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{i.id}}</td>
                    <td>{{i.usuario.first_name}} {{i.usuario.last_name}}</td>
                    <td>{{i.usuario.username}}</td>
                    <a href="/admin-order-track/{{i.id}}/" class="btn btn-primary" title="Track Status">{{i.get_estado_display}}</a>
                    <td>
                        <!-- Botón de activación de modal -->
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal-{{forloop.counter}}">
                            <i class="fas fa-info"></i>
                        </button>
                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal-{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Detalle del pedido</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <table width="100%">
                                            <tr>
                                                <th>ID del Pedido</th>
                                                <td>{{i.id}}</td>
                                                <th>Estado</th>
                                                <td>{{i.get_estado_display}}</td>
                                            </tr>
                                            <tr style="background:black;color:white">
                                                <th colspan="4">Detalle del Producto</th>
                                            </tr>
                                            {% for j in i.producto|get_product %}
                                            <tr>
                                                <th>Producto</th>
                                                <td colspan="2">{{j.name}}</td>
                                                <th>
                                                    <img src="{{j.image.url}}" style="width:100%;height:80px">
                                                </th>
                                            </tr>
                                            <tr>
                                                <th>Cantidad</th>
                                                <td>{% get_qty j.id i.id %}</td>
                                                <th>Precio (por unidad)</th>
                                                <td>Rs. {{j.price}}</td>
                                            </tr>
                                            {% endfor %}
                                            <tr>
                                                <th>Precio Total</th>
                                                <td>Rs. {{i.total}}</td>
                                                <th>Fecha de Reserva</th>
                                                <td>{{i.creado}}</td>
                                            </tr>
                                            <tr>
                                                <th colspan="4" style="background:black;color:white">
                                                    <h4>Detalles del Usuario</h4>
                                                </th>
                                            </tr>
                                            <tr>
                                                <th>Nombre</th>
                                                <td colspan="2">{{i.usuario.first_name}} {{i.usuario.last_name}}</td>
                                                <th>
                                                    <img src="{{i.usuario.userprofile_set.all.0.image.url}}" style="width:100%;height:80px">
                                                </th>
                                            </tr>
                                            <tr>
                                                <th>Correo Electrónico</th>
                                                <td>{{i.usuario.username}}</td>
                                                <th>Móvil</th>
                                                <td>{{i.usuario.userprofile_set.all.0.mobile}}</td>
                                            </tr>
                                            <tr>
                                                <th>Dirección</th>
                                                <td colspan="3">{{i.usuario.userprofile_set.all.0.address}}</td>
                                            </tr>
                                        </table>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a href="/delete-order/{{i.id}}/?action={{request.GET.action}}" class="btn btn-danger" onclick="return confirm('¿Estás seguro?')">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

Tienda/templates/admin_rastreo_ordenes.html
{% extends 'admin_inicio.html' %}
{% load static %}
{% block main %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link href="{% static 'css/progress-bar.css' %}" rel="stylesheet" type="text/css"/>
<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title"> Cambiar Estado del Pedido </h4>
                    <p class="card-description">Dashboard <code>estado-del-pedido</code></p>
                    <hr />
                    <div class="table-responsive">
                        <h4>Rastrear Pedido</h4>
                        <ol class="ProgressBar">
                            {% for i in orderstatus %}
                            <li class="ProgressBar-step {% if i.0 <= order.estado %}is-complete{% endif %}">
                                <svg class="ProgressBar-icon"><use xlink:href="#checkmark-bold"/></svg>
                                <span class="ProgressBar-stepLabel">{{i.1}}</span>
                            </li>
                            {% endfor %}
                        </ol>
                        <div align="right">
                            <button class="btn btn-primary" id="previous" onclick="changestatus('prev')">Anterior</button>
                            <button class="btn btn-info" id="advance" onclick="changestatus('next')">Siguiente</button>
                        </div>
                    </div>
                    <svg xmlns="http://www.w3.org/2000/svg">
                        <symbol id="checkmark-bold" viewBox="0 0 24 24">
                            <path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"/>
                        </symbol>
                    </svg>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script>
function changestatus(data) {
    var orderid = '{{order.id}}';
    var estado = '{{order.estado}}';
    if (data == 'prev') {
        estado = (estado * 1) - 1;
    } else {
        estado = (estado * 1) + 1;
    }
    url = "/admin-order-track/" + orderid + "/?estado=" + estado;
    $.get(url, function(data, status) {
        function statusupdate() {
            window.location.reload();
        }
        setTimeout(statusupdate, 150);
    });
}
</script>
{% endblock %}

Tienda/templates/mi-orden.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <title>Mis Pedidos</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
{% include 'navegacion.html' %}
<hr class="mt-0">
<div class="card shadow m-5" id="myorder">
    <div class="card-body">
        <div class="container-fluid">
            <h3 style="font-family:roman">Mis Pedidos</h3>
            <table class="table table-bordered" style="width:100%">
                <thead>
                <tr>
                    <th>#</th>
                    <th>ID de Reserva</th>
                    <th>Precio Total</th>
                    <th>Estado</th>
                    <th>Fecha de Creación</th>
                    <th>Acción</th>
                </tr>
                </thead>
                <tbody>
                {% for i in order %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{i.id}}</td>
                    <td>{{i.total}}</td>
                    <td><a href="/user-order-track/{{i.id}}/" class="btn btn-primary" title="Rastrear Estado">{{i.get_estado_display}}</a></td>
                    <td>{{i.creado}}</td>
                    <td>
                        {% if i.estado < 4 %}
                            <a href="/change-order-status/{{i.id}}/?status=5" class="btn btn-danger" title="Cancelar Pedido"><i class="fa-solid fa-xmark"></i></a>
                        {% endif %}
                        {% if i.estado == 4 %}
                            <a href="/change-order-status/{{i.id}}/?status=6" class="btn btn-success" title="Devolver Pedido"><i class="fa-solid fa-refresh"></i></a>
                        {% endif %}
                        {% if i.estado == 5 or i.status == 6 %}
                            -----
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
</body>
</html>